# Generated by Django 5.1.7 on 2025-03-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonorCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='centers/')),
            ],
            options={
                'verbose_name': 'Blood Donor Center',
                'verbose_name_plural': 'Blood Donor Centers',
                'db_table': 'blood_donor_centers',
            },
        ),
        migrations.CreateModel(
            name='DonationCenterRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.CharField(choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('count', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_requests', to='blood.blooddonorcenter')),
            ],
            options={
                'verbose_name': 'Donation Center Request',
                'verbose_name_plural': 'Donation Center Requests',
                'db_table': 'donation_center_requests',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('blood_type', models.CharField(choices=[('WB', 'Whole Blood'), ('PS', 'Plasma'), ('PL', 'Platelets'), ('ER', 'Erythrocytes'), ('GR', 'Granulocytes')], max_length=2)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('B', 'Banned')], default='A', max_length=1)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('donation_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_center', to='blood.blooddonorcenter')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'db_table': 'donors',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_full_name', models.CharField(max_length=200)),
                ('recipient_phone_number', models.CharField(max_length=25)),
                ('recipient_address', models.CharField(max_length=200)),
                ('recipient_reference', models.FileField(blank=True, null=True, upload_to='recipient/references/')),
                ('blood_group', models.CharField(choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('blood_type', models.CharField(choices=[('WB', 'Whole Blood'), ('PS', 'Plasma'), ('PL', 'Platelets'), ('ER', 'Erythrocytes'), ('GR', 'Granulocytes')], max_length=2)),
                ('is_urgent', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipient/photos')),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_center', to='blood.blooddonorcenter')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'db_table': 'recipients',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=4)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_donor', to='blood.donor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_recipient', to='blood.recipient')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
            },
        ),
    ]
