# Generated by Django 5.1.7 on 2025-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonorcenter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonorcenter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
