# Generated by Django 5.1.7 on 2025-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_alter_blooddonorcenter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenterrequests',
            name='any_blood_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationcenterrequests',
            name='donor_blood_type',
            field=models.CharField(choices=[('WB', 'Whole Blood'), ('PS', 'Plasma'), ('PL', 'Platelets'), ('ER', 'Erythrocytes'), ('GR', 'Granulocytes')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationcenterrequests',
            name='donor_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationcenterrequests',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
    ]
