# Generated by Django 5.1.7 on 2025-03-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_donationcenterrequests_any_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenterrequests',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
