# Generated by Django 5.1.7 on 2025-03-14 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_donationcenterrequests_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Advice',
                'verbose_name_plural': 'Donor Advices',
                'db_table': 'donor_advices',
            },
        ),
    ]
