# Generated by Django 5.2 on 2025-04-18 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_donoradvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcenterrequests',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('0plus', '0(I) Rh+'), ('0minus', '0(I) Rh-'), ('Aplus', 'A(II) Rh+'), ('Aminus', 'A(II) Rh-'), ('Bplus', 'B(III) Rh+'), ('Bminus', 'B(III) Rh-'), ('ABplus', 'AB(IV) Rh+'), ('ABminus', 'AB(IV) Rh-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('0plus', '0(I) Rh+'), ('0minus', '0(I) Rh-'), ('Aplus', 'A(II) Rh+'), ('Aminus', 'A(II) Rh-'), ('Bplus', 'B(III) Rh+'), ('Bminus', 'B(III) Rh-'), ('ABplus', 'AB(IV) Rh+'), ('ABminus', 'AB(IV) Rh-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='blood_group',
            field=models.CharField(choices=[('0plus', '0(I) Rh+'), ('0minus', '0(I) Rh-'), ('Aplus', 'A(II) Rh+'), ('Aminus', 'A(II) Rh-'), ('Bplus', 'B(III) Rh+'), ('Bminus', 'B(III) Rh-'), ('ABplus', 'AB(IV) Rh+'), ('ABminus', 'AB(IV) Rh-')], max_length=10),
        ),
        migrations.CreateModel(
            name='UrgentDonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_components', models.CharField(choices=[('WB', 'Whole blood'), ('PS', 'Plasma'), ('PL', 'Platelets'), ('ER', 'Erythrocytes'), ('GR', 'Granulocytes')], max_length=2)),
                ('blood_group', models.CharField(choices=[('0plus', '0(I) Rh+'), ('0minus', '0(I) Rh-'), ('Aplus', 'A(II) Rh+'), ('Aminus', 'A(II) Rh-'), ('Bplus', 'B(III) Rh+'), ('Bminus', 'B(III) Rh-'), ('ABplus', 'AB(IV) Rh+'), ('ABminus', 'AB(IV) Rh-')], max_length=10)),
                ('donor_count', models.PositiveIntegerField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='urgent_requests/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.blooddonorcenter')),
            ],
            options={
                'verbose_name': 'Urgent Donor Request',
                'verbose_name_plural': 'Urgent Donor Requests',
                'db_table': 'urgent_donor_requests',
            },
        ),
    ]
