# Generated by Django 5.2 on 2025-04-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_alter_donationcenterrequests_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentDonorRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_donor_history', to='blood.donor')),
                ('urgent_donor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='blood.urgentdonorrequest')),
            ],
            options={
                'verbose_name': 'Urgent Donor Request History',
                'verbose_name_plural': 'Urgent Donor Request Histories',
                'db_table': 'urgent_donor_request_histories',
            },
        ),
    ]
