# Generated by Django 5.2 on 2025-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_urgentdonorrequesthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentdonorrequesthistory',
            name='donation_date',
            field=models.DateField(),
        ),
    ]
