# Generated by Django 5.2 on 2025-04-18 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_alter_urgentdonorrequesthistory_donation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentdonorrequesthistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urgentdonorrequesthistory',
            name='urgent_donor_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_donor_request', to='blood.urgentdonorrequest'),
        ),
    ]
