# Generated by Django 5.2 on 2025-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
